### ISSUE TITLE
Installer fails on PHP7

### ISSUE THREAD

**Issue by danelowe** [CodistoConnect/CodistoConnect#239]
in `app/code/community/Codisto/Sync/data/codisto_setup/data-install-1.1.74.php` There are keywords `continue` and `break` outside of a loop, which causes PHP7 to bail.

**Comment by lamery** [comment]
Thanks Dane!

I'll get this sorted out shortly

**Comment by lamery** [comment]
Hi Dane,

We happened to have been preparing a PR that cleaned up the registration / data-install code

https://github.com/CodistoConnect/CodistoConnect/pull/241

It addresses the issue of those dangling continue / break statements

This has been merged to master, plugin is updated on our website and uploaded to MagentoConnect

Let me know if you have further issues with PHP7 deployment
